### PR TITLE
revert to using hex for fill colors instead of RGBA

### PR DESCRIPTION
**Pull request by tlnagy**
2nd part of #322

### CODE REVIEW

**Comment by bjarthur** [comment]
bump

**Comment by bjarthur** [comment]
is this ready to merge?  or is it stale?

**Comment by Mattriks** [comment]
The function `svgalphatest` needs to be added to this PR.  See [this post](https://github.com/GiovineItalia/Compose.jl/issues/322#issuecomment-433741922) and the subsequent posts. If you merge this PR, I can add `svgalphatest` in another PR?

**Comment by tlnagy** [comment]
As @Mattriks says, this PR needs to throw a warning to alert users to the change in behavior.

> If you merge this PR, I can add svgalphatest in another PR?

This is fine, IMO

**Comment by bjarthur** [comment]
@Mattriks add the test and then we can tag

**Comment by Mattriks** [comment]
The above merge had a side-effect: the `fill(nothing)` statement in a parent context now clobbers the fill(color) statement in a nested context (for svg).  See the 2 examples in the [Transformations gallery](http://giovineitalia.github.io/Compose.jl/dev/gallery/transforms/), which both use nested contexts.  I should be able to sort that out.

**Pull request merged**
