### PR TITLE
finish port to julia 0.6

### PR DESCRIPTION
**Pull request by bjarthur**
this simply adds one more commit to https://github.com/GiovineItalia/Compose.jl/pull/239 which removes the remaining dep warns.  one can now cleanly `using Compose` on julia 0.5 and 0.6.

while tests pass on 0.6, they currently don't for 0.5, neither for the master branch of Compose nor this PR:

```
julia> Pkg.test("Compose")
INFO: Computing test dependencies for Compose...
INFO: No packages to install, update or remove
INFO: Testing Compose
Test Failed
  Expression: ((text_extents(font_family,8pt,"test test"))[1])[2] * 2 == ((text_extents(font_family,8pt,"test\ntest"))[1])[2]
   Evaluated: 3.7758246527777772mm == 5.206917317708333mm
```

but that is a separate issue...

### CODE REVIEW

**Comment by bjarthur** [comment]
tests pass on 0.5 and nightly.  will merge in a couple days unless someone has a concern.

the `text_extents` failure mentioned above appears to be something peculiar to my local machine.  i also experience another failure locally involving small differences in the generated .svg files which have no impact on the visual appearance.  but travis is happy, so so am i.

**Comment by tlnagy** [comment]
@bjarthur Thanks for taking the time to update my PR. I'm working on getting `Measures.jl` working right now. It looks like we're closing in on getting the Gadfly stack onto 0.6! 🎉

**Comment by tlnagy** [comment]
Also, the `text_extents` failures could be due to you having slightly different fonts being used then the Travis Linux boxes.

**Comment by bjarthur** [comment]
i've got measures working already.  just need to push the PR

**Comment by tlnagy** [comment]
Ah. Well I have PR here: https://github.com/JuliaGraphics/Measures.jl/pull/12 waiting for it to pass tests.

**Pull request merged**
