### PR TITLE
WIP: remove more julia 0.6 dep warns

### PR DESCRIPTION
**Pull request by bjarthur**
they're might be more so don't merge yet

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like you got all of the warnings that would be caught by the tests. 👍

**Comment by bjarthur** [comment]
yea, but, when Gadfly's tests are run, more Compose dep warns appear.  so Compose's tests are not complete.  and i can't yet get all of Gadfly's tests to finish yet without errors.

**Comment by ararslan** [comment]
Ah, I see. Thanks for working on this. I'm looking forward to using Gadfly on 0.6. 🙂

**Comment by bjarthur** [comment]
all Gadfly tests pass locally now on julia 0.6 with this Compose PR.  for the Gadfly travis tests to pass on nightly, we're going to need to tag a new release of Compose i think.  since version 0.4.5 we've:

1. stripped out old precompilation code
2. dropped support for 0.4 and added same for 0.6
3. upgraded to new documentation system

shall i merge this PR and tag a release?  any thoughts on a new version number?

**Comment by ararslan** [comment]
+1 for merging and tagging. Since support for Julia 0.4 has been dropped since the last tag, the next tag will need to bump the minor version. That is, since the current tag is v0.4.5, the next should be v0.5.0 per METADATA (and SemVer) requirements.

**Comment by tlnagy** [comment]
You'll need to do

```
PkgDev.tag("Compose", :minor)
PkgDev.publish("Compose")
```

as @ararslan points out

**Comment by ararslan** [comment]
...or use [attobot](https://github.com/attobot/attobot), if it's set up for this organization. 😉

**Comment by tlnagy** [comment]
Good point, I just installed attobot for GiovineItalia

**Pull request merged**
