### PR TITLE
updated #267 and fixed printing error

### PR DESCRIPTION
**Pull request by tlnagy**
this takes @dcjones' work in #267 and updates it for Julia 1.0 and fixes the bug pointed out by @bjarthur, fixes https://github.com/GiovineItalia/Gadfly.jl/issues/770

### CODE REVIEW

**Comment by tlnagy** [comment]
All Gadfly tests pass with this PR, I haven't had time to do full regression testing.

**Comment by tlnagy** [comment]
This has some conflicts with #314, @Mattriks any thoughts on how to handle https://github.com/GiovineItalia/Compose.jl/pull/315/files#diff-515ba812075dc0588b80962eb71ad83eR294?

**Comment by Mattriks** [comment]
#314 already (inadvertently) fixes the issue in #267 for PNG, but not for SVG.  Try this example (on the latest masters):
```
set_default_graphic_size(14cm,4cm)
img2 = compose(context(), fill(["purple","purple"]),
    (context(), circle(0.5, 0.5, 0.08), fill("orange"), fillopacity(0.3)),
    (context(), circle([0.1, 0.26], [0.5], [0.1]), fillopacity(0.3), fill("blue")),
   (context(), circle([0.42, 0.58], [0.5], [0.1]), fill(["yellow","green"]), fillopacity(0.3)),
    (context(), circle([0.74, 0.90], [0.5], [0.1]),  fillopacity([0.5,0.3]), fill(["yellow","red"]))
)

draw(PNG(), img2)
draw(SVG(), img2)
```
There should be no purple circles in the PNG, but in SVG, the blue and orange circles get changed to purple.  So in this PR, just fix the problem for SVG and PGF.

**Comment by bjarthur** [comment]
bump

**Comment by tlnagy** [comment]
I think this is ready to be merged. I added a test to verify that the scalar color properly clobbers the vector colors in the final SVG output.

**Pull request merged**
