### PR TITLE
use Requires

### LINKED ISSUE #221: Static compilation fails on Compose.jl
I’m trying to create a system image of Julia with Compose.jl embedded, I encountered following error while building Julia (using release-0.5 branch).

```
â  make -j 4
    JULIA usr/lib/julia/sys.o
coreio.jl
exports.jl
essentials.jl
base.jl
generator.jl
reflection.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
refpointer.jl
WARNING: Method definition (::Type{#T<:Any})(Any) in module Inference at coreimg.jl:39 overwritten in module Base at sysimg.jl:53.
checked.jl
abstractarray.jl
subarray.jl
array.jl
hashing.jl
rounding.jl
float.jl
complex.jl
rational.jl
multinverses.jl
abstractarraymath.jl
arraymath.jl
float16.jl
simdloop.jl
reduce.jl
reshapedarray.jl
bitarray.jl
intset.jl
dict.jl
set.jl
iterator.jl
build_h.jl
version_git.jl
osutils.jl
c.jl
sysinfo.jl
io.jl
iostream.jl
iobuffer.jl
char.jl
intfuncs.jl
strings/strings.jl
strings/errors.jl
strings/string.jl
strings/types.jl
strings/basic.jl
strings/search.jl
strings/util.jl
strings/io.jl
strings/utf8proc.jl
parse.jl
shell.jl
regex.jl
pcre.jl
show.jl
base64.jl
nullable.jl
version.jl
libc.jl
libdl.jl
env.jl
libuv.jl
uv_constants.jl
event.jl
task.jl
lock.jl
threads.jl
weakkeydict.jl
stream.jl
socket.jl
filesystem.jl
process.jl
multimedia.jl
grisu/grisu.jl
methodshow.jl
floatfuncs.jl
math.jl
cartesian.jl
multidimensional.jl
permuteddimsarray.jl
reducedim.jl
ordering.jl
collections.jl
sort.jl
WARNING: Method definition searchsortedfirst(AbstractArray{T<:Any, 1}, Any) in module Sort at sort.jl:184 overwritten at sort.jl:187.
WARNING: Method definition searchsortedlast(AbstractArray{T<:Any, 1}, Any) in module Sort at sort.jl:184 overwritten at sort.jl:187.
WARNING: Method definition searchsorted(AbstractArray{T<:Any, 1}, Any) in module Sort at sort.jl:184 overwritten at sort.jl:187.
gmp.jl
mpfr.jl
combinatorics.jl
hashing2.jl
dSFMT.jl
random.jl
printf.jl
meta.jl
Enums.jl
serialize.jl
channels.jl
clusterserialize.jl
multi.jl
workerpool.jl
pmap.jl
managers.jl
asyncmap.jl
loading.jl
mmap.jl
sharedarray.jl
datafmt.jl
deepcopy.jl
interactiveutil.jl
replutil.jl
test.jl
i18n.jl
initdefs.jl
Terminals.jl
LineEdit.jl
REPLCompletions.jl
REPL.jl
client.jl
util.jl
linalg/linalg.jl
broadcast.jl
statistics.jl
irrationals.jl
dft.jl
dsp.jl
quadgk.jl
fastmath.jl
libgit2/libgit2.jl
pkg/pkg.jl
stacktraces.jl
profile.jl
dates/Dates.jl
sparse/sparse.jl
threadcall.jl
deprecated.jl
docs/helpdb.jl
docs/helpdb/Base.jl
docs/basedocs.jl
markdown/Markdown.jl
docs/Docs.jl
/home/julia/JuliaUserImage_image/julia/base/precompile.jl
WARNING: could not import StructIO.pack into COFF
WARNING: could not import Base.lastidx into LegacyStrings
WARNING: Method definition XML_ErrorString(Any) in module LibExpat at /home/julia/JuliaUserImage_packages/v0.5/LibExpat/src/lX_common_h.jl:4 overwritten at /home/julia/JuliaUserImage_packages/v0.5/LibExpat/src/lX_common_h.jl:4.
WARNING: Method definition abs2(DualNumbers.Dual4) in module DualNumbers at /home/julia/JuliaUserImage_packages/v0.5/DualNumbers/src/dual_n.jl:78 overwritten at /home/julia/JuliaUserImage_packages/v0.5/DualNumbers/src/dual_n.jl:154.
WARNING: requiring "Dates" in module "Main" did not define a corresponding module.
WARNING: Method definition info(Any...) in module Base at util.jl:320 overwritten in module Logging at /home/julia/JuliaUserImage_packages/v0.5/Logging/src/Logging.jl:61.
WARNING: Method definition warn(Any...) in module Base at util.jl:350 overwritten in module Logging at /home/julia/JuliaUserImage_packages/v0.5/Logging/src/Logging.jl:61.
WARNING: Method definition pvalue(HypothesisTests.FisherTLinearAssociation) in module HypothesisTests at /home/julia/JuliaUserImage_packages/v0.5/HypothesisTests/src/circular.jl:139 overwritten at /home/julia/JuliaUserImage_packages/v0.5/HypothesisTests/src/circular.jl:139.
WARNING: Method definition #pvalue(Array{Any, 1}, HypothesisTests.#pvalue, HypothesisTests.FisherTLinearAssociation) in module HypothesisTests overwritten.
WARNING: Method definition pvalue(HypothesisTests.FisherTLinearAssociation) in module HypothesisTests at /home/julia/JuliaUserImage_packages/v0.5/HypothesisTests/src/circular.jl:139 overwritten at /home/julia/JuliaUserImage_packages/v0.5/HypothesisTests/src/circular.jl:139.
WARNING: Method definition #pvalue(Array{Any, 1}, HypothesisTests.#pvalue, HypothesisTests.FisherTLinearAssociation) in module HypothesisTests overwritten.
WARNING: `@unix_only` is deprecated, use `@static if is_unix()` instead
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in @unix_only(::Any) at ./deprecated.jl:492
 in include_from_node1(::String) at ./loading.jl:488
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
 in include_from_node1(::String) at ./loading.jl:488
 in exec_program at /home/julia/JuliaUserImage_image/julia/ui/repl.c:66
 in true_main at /home/julia/JuliaUserImage_image/julia/ui/repl.c:119
 in main at /home/julia/JuliaUserImage_image/julia/ui/repl.c:232
while loading /home/julia/JuliaUserImage_packages/v0.5/Zlib/src/Zlib.jl, in expression starting on line 28
LoadError("sysimg.jl",381,LoadError("/home/julia/JuliaUserImage_image/julia/base/userimg.jl",2,LoadError("/home/julia/JuliaUserImage_packages/v0.5/Compose/src/Compose.jl",174,BoundsError(String[],(1,)))))
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/home/julia/JuliaUserImage_image/julia/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2 
```

OS = Ubuntu 14.04
Compose version = 0.4.4

### PR DESCRIPTION
**Pull request by shashi**
this seems to fix #221

### CODE REVIEW

**Comment by tkelman** [comment]
I think creating a separate ComposeCairo package will be more reliable than Requires in terms of interaction with precompilation today.

**Comment by tlnagy** [comment]
Now that we have a separate org, this is actually reasonably easy to do. hey @shashi, I invited you to be a org member a while back. Did you get the email?

**Comment by tlnagy** [comment]
bump

**Comment by tlnagy** [comment]
This was implemented in #282

**Pull request closed without merging**
