### PR TITLE
Update the TagBot configuration

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @GiovineItalia

### CODE REVIEW

**Comment by DilumAluthge** [comment]
It will be good to merge this ASAP.

**Comment by DilumAluthge** [comment]
Also cc: @bjarthur

**Comment by bjarthur** [comment]
thanks!  mind doing this for Gadfly.jl as well?

**Comment by DilumAluthge** [comment]
https://github.com/GiovineItalia/Gadfly.jl/pull/1517

**Comment by bjarthur** [comment]
@DilumAluthge i just noticed you commented out `ssh: ${{ secrets.DOCUMENTER_KEY }}` in this PR.  what was the reason for doing so?  thanks.

**Comment by DilumAluthge** [comment]
Oops that was accidental. You should uncommemt it.

**Pull request merged**
