### PR TITLE
Drop some IterTools methods for Base.Iterators methods

### PR DESCRIPTION
**Pull request by iamed2**
These two _might_ get deprecated in IterTools so I want to make sure they aren't necessary. 

Note that the ordering for Base.Iterators.product is different than the ordering for IterTools.product, and there are no Compose tests which follow that path.

### CODE REVIEW

**Comment by iamed2** [comment]
Looks like Gadfly tests caught that Compose was expecting `product()` to exist

**Comment by iamed2** [comment]
Alright, this should work now.

**Comment by bjarthur** [comment]
there might be Gadfly tests which would test the differing order in `product`.  might try running the [regressions tests](http://gadflyjl.org/latest/dev/regression.html).

**Comment by iamed2** [comment]
Okay will do! The regular Gadfly tests did pass with this change.

**Comment by iamed2** [comment]
Regression tests pass! :)

**Comment by bjarthur** [comment]
thanks!

**Pull request merged**
