### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by CiaranOMara**
- ~~Add Julia 1.3 to test matrix.~~
- Use the codecov flag in Travis instead of the manual code version.
- Pkg.instantiate after  Pkg.develop.
- Add colour to make doc output.

### CODE REVIEW

**Comment by bjarthur** [comment]
i'd suggest waiting to merge this until after julia 1.3 comes out, and then not testing compose on 1.2 anymore.  it might be awhile, as there is an [RC5 planned](https://github.com/JuliaLang/julia/pull/33630).

**Comment by CiaranOMara** [comment]
I removed Julia v1.3 from the test matrix so as not to be held up by RC5.

**Comment by bjarthur** [comment]
was doing `instantiate` before `develop` causing a problem?  i can't think of a reason why the order would matter.

**Comment by CiaranOMara** [comment]
I don't think the order would have caused any issues as both `Pkg.develop()` and `Pkg.instantiate()` should upgrade or downgrade packages as required, and I assume `Pkg.jl` would arrive at the same solution irrespective of order. In the end, this just matches the order in the [Documenter.jl hosting example](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#.travis.yml-Configuration-1).

**Pull request merged**
